# routes.yml holds information that allows the agent to render a form
# on a web page to collect information about a credential to be
# issued. While not normally used in a production use case (a service
# likely already has data collection capabilities), the form is useful
# for testing purposes and for use with GreenLight.
#
# @see https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

forms:
  gpid-reg:
    path: /gpid/registration
    type: issue-credential
    schema_name: Registered General Practitioner
    page_title: General Practitioner ID Registry
    title: Registration
    template: bcgov.index.html
    description: >
      The College of Physicians and Surgeons of British Columbia
      regulates the practice of medicine under the authority of
      provincial law. All physicians who practise medicine in
      the province must be registrants of the College.
    explanation: Use the form below to register a General Practitioner ID (GPID).

    fields:
      - name: gpid
        label: General Practitioner ID
        type: text
        required: true

      # TODO what fields should be included?
      # - name: legal_name
      #   label: General Practitioner ID
      #   type: text
      #   required: true

    mapping:
      # TODO what fields should be included?
      attributes:
        - name: registration_date
          from: helper
          source: now_iso
