# schemas.yml holds the schema attributes for the set of credentials
# to be issued by the agent. Based on this information, the agent
# can, on startup, look up on, and if necessary, publish to, the
# ledger the schema and credential definitions for the credentials
# to be issued by the agent.
#
# @see https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: GPID
  version: '1.0.1'
  attributes:
    - gpid
    # TODO what attributes should be included?
    # - legal_name
