forms:
  bcsc-info:
    path: /bcsc/registration
    type: issue-credential
    schema_name: BCSC Information
    page_title: BC Services Card
    title: BCSC
    template: bcgov.index.html
    description: >
      The BC Services Card provides access to government services. It replaces the CareCard for access to health care services.
    explanation: Use the form below to register a BC Services Card.

    fields:
      - name: hpdid
        label: HPDID
        type: text
        required: true

      - name: user_id
        label: User ID
        type: text
        required: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true

      # - name: first_name
      #   label: First Name
      #   type: text
      #   required: true

      # - name: last_name
      #   label: Last Name
      #   type: text
      #   required: true

    mapping:
      attributes:
        - name: entity_name_effective
          from: helper
          source: now_iso

