- name: BCSC Information
  version: '1.0.3'
  attributes:
    - userId
    - hpdid
    - fistName
    - lastName
    - entity_name_effective

- name: Business Relationship
  version: '1.0.3'
  attributes:
    - corp_num
    - dba_corp_num
    - relationship
    - relationship_description
    - relationship_status
    - relationship_status_effective
    - effective_date
    - reason_description
