# File Format Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: BCSC Information
  version: '1.0.0'
  description: BCSC Information

  attributes:
    - userId
    - hpdid
    - fistName
    - lastName
    - effective_date
