# routes.yml holds information that allows the agent to render a form
# on a web page to collect information about a credential to be
# issued. While not normally used in a production use case (a service
# likely already has data collection capabilities), the form is useful
# for testing purposes and for use with GreenLight.
#
# @see https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

forms:
  cpbc:
    path: /cpbc/registration
    type: issue-credential
    schema_name: Registered Pharmacist
    page_title: College of Pharmacists of BC Registry
    title: Registration
    template: bcgov.index.html
    description: >
      The College of Pharmacists of British Columbia protects the public
      by ensuring that registered pharmacy professionals provide safe
      and effective pharmacy care.
    explanation: Use the form below to register with the College of Pharmacists of BC

    # Automatically fill from the claim by mapping it to the form
    proof_request:
      id: registration
      connection_id: bctob

    fields:
      - name: hpdid
        label: HPDID
        type: text
        required: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true

      # TODO what fields should be included?
      # - name: address
      #   label: Mailing Address
      #   type: address
      #   required: true

      # TODO college prefix of P1 should be applied automatically or to view
      - name: licence_num
        label: Licence Number
        type: text
        required: true

      - name: licence_class
        label: Licence Class
        type: select
        options:
          - Full Pharmacist
          - Limited Pharmacist
          - Student Pharmacist
          - Temporary Pharmacist
          - Non-Practicing Pharmacist
        required: true

    mapping:
      # TODO what fields should be included?
      attributes:
        - name: registration_date
          from: helper
          source: now_iso
