# services.yml defines how attributes in the credentials issued by
# the agent should be processed by OrgBook. This includes the
# mapping of attributes to OrgBook search indices and the
# localization of strings in the UI for each credential.
#
# @see https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  cpbc:
    logo_path: ''
    name: College of Pharmacists of BC Registry
    abbreviation: CPBC
    email: cpbc.test.issuer@example.ca
    url: https://www.bcpharmacists.org
    endpoint: ${ENDPOINT_URL}/cpbc

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-cpbc_issuer}
      seed: $INDY_WALLET_SEED
      type: $INDY_WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: Registration
        schema: Registered Pharmacist
        issuer_url: $APPLICATION_URL/cpbc/registration
        depends_on:
          - registration
        topic:
          source_id:
            # Glue between credentials from root
            input: hpdid
            from: claim
          type:
            # Name of the proof request (see below)
            # - Will be a value that automatically fills
            input: registration
            from: value
        # TODO how is this mapped?
        # mapping:
          # TODO name vs attribute?
          # - model: name
          #   fields:
          #     text:
          #       input: last_name
          #       from: claim
          #     type:
          #       input: last_name
          #       from: value
          # - model: attribute
          #   fields:
          #     text:
          #       input: licence_num
          #       from: claim
          #     type:
          #       input: licence_num
          #       from: value

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.7'
    schemas:
      - key:
          did: TpUxciSx8mQQULW3uspf7p
          name: BCSC Information
          version: '1.0.7'
        attributes:
          - hpdid
          # - legal_name
          # - first_name
          # - last_name
